#!/usr/bin/env bash
# Renders the deployment's patch overlay from the environment, then boots the
# web profile with it.
#
# Everything this file writes goes through the official patch layer: the
# `webserver` row binds beyond loopback (the `--host 0.0.0.0` flag is refused by
# the CLI by design), the `connection` row declares the authorities this
# deployment answers to, and the two inserted rows mount the authentication seam
# and its password provider. No installed file is modified.
set -euo pipefail

PORT="${DSH_PORT:-3080}"
BIND="${DSH_BIND:-0.0.0.0}"
CONFIG="${DSH_HOME}/docker.cordis.yml"

if [ ! -w "${DSH_HOME}" ]; then
  echo "dsh-entrypoint: ${DSH_HOME} is not writable by uid $(id -u); mount it writable by uid 1000" >&2
  exit 1
fi

# `trustedHosts` cannot be derived here: the CLI only infers LAN literals for its
# own --host flag, which this image does not use. An empty list keeps the
# deployment loopback-only, which is the safe default for a missing variable.
render_trusted_hosts() {
  local raw="${DSH_TRUSTED_HOST:-}"
  if [ -z "${raw}" ]; then
    echo "    trustedHosts: []"
    return
  fi
  echo "    trustedHosts:"
  local host
  while IFS= read -r host; do
    [ -n "${host}" ] || continue
    echo "      - '${host}'"
  done < <(echo "${raw}" | tr ',' '\n' | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')
}

{
  echo "# Generated by dsh-entrypoint on container start; edits are overwritten."
  echo "- id: webserver"
  echo "  config:"
  echo "    host: ${BIND}"
  echo "    port: ${PORT}"
  echo
  echo "- id: connection"
  echo "  config:"
  render_trusted_hosts
  echo
  echo "- insert:"
  echo "    - id: web-auth"
  echo "      name: '@deepseek-ai/dsh-host-web-auth'"
  echo "      config:"
  echo "        cookieSecure: ${DSH_COOKIE_SECURE:-auto}"
  echo "        sessionTtlSeconds: ${DSH_SESSION_TTL_SECONDS:-43200}"
  echo
  echo "    - id: web-auth-password"
  echo "      name: '@deepseek-ai/dsh-host-web-auth-password'"
  echo "      config:"
  echo "        file: !!js dshHomePath('web-auth', 'password.json')"
  echo "        maxAttempts: ${DSH_AUTH_MAX_ATTEMPTS:-5}"
  echo "        lockoutSeconds: ${DSH_AUTH_LOCKOUT_SECONDS:-300}"
} > "${CONFIG}"

if [ "${DSH_PRINT_CONFIG:-0}" = "1" ]; then
  echo "dsh-entrypoint: rendered ${CONFIG}" >&2
  sed 's/^/  /' "${CONFIG}" >&2
fi

# The generated password prints on first start only; it is unrecoverable
# afterwards, so container logs are the one delivery channel.
exec node /opt/dsh/apps/cli/lib/bin.js web --patch "${CONFIG}" "$@"
