#!/usr/bin/env bash
# Renders the deployment's patch overlay from the environment, then boots the
# web profile with it.
#
# Everything this file writes goes through the official patch layer: the
# `webserver` row binds beyond loopback (the `--host 0.0.0.0` flag is refused by
# the CLI by design), the `connection` row declares the authorities this
# deployment answers to, and the inserted rows mount the authentication seam and
# whichever providers this deployment enables. No installed file is modified.
set -euo pipefail

PORT="${DSH_PORT:-3080}"
BIND="${DSH_BIND:-0.0.0.0}"
CONFIG="${DSH_HOME}/docker.cordis.yml"
PASSWORD_PROVIDER="${DSH_WEB_AUTH_PASSWORD:-1}"
CF_TEAM="${DSH_CF_ACCESS_TEAM:-}"
CF_AUD="${DSH_CF_ACCESS_AUD:-}"

if [ ! -w "${DSH_HOME}" ]; then
  echo "dsh-entrypoint: ${DSH_HOME} is not writable by uid $(id -u); mount it writable by uid 1000" >&2
  exit 1
fi

# A leftover root-owned overlay makes the directory look writable while the
# redirect below fails; say so once instead of failing on every restart.
if [ -e "${CONFIG}" ] && [ ! -w "${CONFIG}" ]; then
  echo "dsh-entrypoint: ${CONFIG} exists but is not writable by uid $(id -u)." >&2
  echo "  It was written by a container that ran as root. Delete it, or recreate the volume." >&2
  exit 1
fi

if { [ -n "${CF_TEAM}" ] && [ -z "${CF_AUD}" ]; } || { [ -z "${CF_TEAM}" ] && [ -n "${CF_AUD}" ]; }; then
  echo "dsh-entrypoint: set both DSH_CF_ACCESS_TEAM and DSH_CF_ACCESS_AUD, or neither" >&2
  exit 1
fi

# Refuse the one composition that looks configured and protects nothing: reachable
# under a declared authority with no provider mounted leaves `required` false, so
# the fence admits that authority exactly as it did before authentication existed.
if [ -n "${DSH_TRUSTED_HOST:-}" ] && [ "${PASSWORD_PROVIDER}" != "1" ] && [ -z "${CF_TEAM}" ]; then
  echo "dsh-entrypoint: DSH_TRUSTED_HOST is set but no provider is enabled — that would serve" >&2
  echo "  the declared authority without authentication. Enable DSH_WEB_AUTH_PASSWORD=1 or" >&2
  echo "  configure DSH_CF_ACCESS_TEAM/DSH_CF_ACCESS_AUD." >&2
  exit 1
fi

# `trustedHosts` cannot be derived here: the CLI only infers LAN literals for its
# own --host flag, which this image does not use. An empty list keeps the
# deployment loopback-only, which is the safe default for a missing variable.
render_trusted_hosts() {
  local raw="${DSH_TRUSTED_HOST:-}"
  if [ -z "${raw}" ]; then
    echo "    trustedHosts: []"
    return
  fi
  echo "    trustedHosts:"
  local host
  while IFS= read -r host; do
    [ -n "${host}" ] || continue
    echo "      - '${host}'"
  done < <(echo "${raw}" | tr ',' '\n' | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')
}

{
  echo "# Generated by dsh-entrypoint on container start; edits are overwritten."
  echo "- id: webserver"
  echo "  config:"
  echo "    host: ${BIND}"
  echo "    port: ${PORT}"
  echo
  echo "- id: connection"
  echo "  config:"
  render_trusted_hosts
  echo
  echo "- insert:"
  echo "    - id: web-auth"
  echo "      name: '@deepseek-ai/dsh-host-web-auth'"
  echo "      config:"
  echo "        cookieSecure: ${DSH_COOKIE_SECURE:-auto}"
  echo "        sessionTtlSeconds: ${DSH_SESSION_TTL_SECONDS:-43200}"

  if [ "${PASSWORD_PROVIDER}" = "1" ]; then
    echo
    echo "    - id: web-auth-password"
    echo "      name: '@deepseek-ai/dsh-host-web-auth-password'"
    echo "      config:"
    echo "        file: !!js dshHomePath('web-auth', 'password.json')"
    echo "        maxAttempts: ${DSH_AUTH_MAX_ATTEMPTS:-5}"
    echo "        lockoutSeconds: ${DSH_AUTH_LOCKOUT_SECONDS:-300}"
  fi

  if [ -n "${CF_TEAM}" ]; then
    echo
    echo "    - id: web-auth-cloudflare-access"
    echo "      name: '@deepseek-ai/dsh-host-web-auth-cloudflare-access'"
    echo "      config:"
    echo "        teamDomain: '${CF_TEAM}'"
    echo "        audience: '${CF_AUD}'"
    if [ -n "${DSH_CF_ACCESS_CERTS_URL:-}" ]; then
      echo "        certsUrl: '${DSH_CF_ACCESS_CERTS_URL}'"
    fi
  fi
} > "${CONFIG}"

if [ "${DSH_PRINT_CONFIG:-0}" = "1" ]; then
  echo "dsh-entrypoint: rendered ${CONFIG}" >&2
  sed 's/^/  /' "${CONFIG}" >&2
fi

# The generated password prints on first start only; it is unrecoverable
# afterwards, so container logs are the one delivery channel.
exec node /opt/dsh/apps/cli/lib/bin.js web --patch "${CONFIG}" "$@"
